project:
  title: "Quarto Template"

author: "Ishmael Roslan"
format:
  html: 
    theme: html_theme.scss
    dev: ragg_png
    link-external-newwindow: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 4
    toc-location: right
    toc-title: "On this page"
    number-sections: true
    smooth-scroll: true
    link-external-icon: true
    code-overflow: wrap
    code-summary: "Show/Hide Code"
    code-link: true
    code-tools: true
    code-fold: show
    code-copy: true
    code-line-numbers: true
    highlight-style: dracula
    df-print: paged
    filters: 
      - lightbox
    lightbox: auto
    fig-cap-location: top
execute: 
  warning: false
  error: false
editor: 
  markdown: 
    wrap: 120

