project:
  title: "Quarto Template"


author: "Ishmael Roslan"
format:
  html: 
    theme: html_theme.scss
    dev: ragg_png
    link-external-newwindow: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 4
    toc-location: right
    toc-title: "On this page"
    number-sections: true
    smooth-scroll: true
    link-external-icon: true
    code-overflow: wrap
    code-summary: "Show/Hide Code"
    code-link: true
    code-tools: true
    code-fold: show
    code-copy: true
    code-line-numbers: true
    highlight-style: dracula
    df-print: paged
    fig-cap-location: top
  docx:
    reference-doc: unifrog.docx
    dev: ragg_png
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    highlight-style: dracula
    page-width: 7
    fig-width: 7
    fig-align: center
    fig-format: png
    fig-asp: 0.625
execute: 
  warning: false
  error: false
  echo: false
  freeze: auto
editor: 
  markdown: 
    wrap: 120

